//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntervencoesEquipas
    {
        public int equipa { get; set; }
        public int intervencao { get; set; }
        public System.DateTime dtAtribuicao { get; set; }
        public Nullable<System.DateTime> dtDispensa { get; set; }
    
        public virtual Equipas Equipas { get; set; }
        public virtual Intervencoes Intervencoes { get; set; }
    }
}
