//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumoIntervencoes
    {
        public Nullable<long> id { get; set; }
        public string estadoIntervencoes { get; set; }
        public decimal vlMonetarioIntervencoes { get; set; }
        public System.DateTime dtInicioIntervencoes { get; set; }
        public Nullable<System.DateTime> dtFimIntervencoes { get; set; }
        public int perMesesIntervencoes { get; set; }
        public string nomeActivos { get; set; }
        public System.DateTime dtAquisicaoActivos { get; set; }
        public byte estadoActivos { get; set; }
        public string marcaActivos { get; set; }
        public string modeloActivos { get; set; }
        public string localizacaoActivos { get; set; }
        public int funcionarioActivos { get; set; }
        public int tipoActivos { get; set; }
    }
}
