//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionariosEquipas
    {
        public int funcionario { get; set; }
        public int equipa { get; set; }
        public System.DateTime dtEntrada { get; set; }
        public Nullable<System.DateTime> dtSaida { get; set; }
    
        public virtual Equipas Equipas { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
    }
}
