//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervencoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intervencoes()
        {
            this.IntervencoesEquipas = new HashSet<IntervencoesEquipas>();
        }
    
        public int id { get; set; }
        public int competencias { get; set; }
        public string estado { get; set; }
        public int activo { get; set; }
        public decimal vlMonetario { get; set; }
        public System.DateTime dtInicio { get; set; }
        public Nullable<System.DateTime> dtFim { get; set; }
        public int perMeses { get; set; }
    
        public virtual Activos Activos { get; set; }
        public virtual Competencias Competencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntervencoesEquipas> IntervencoesEquipas { get; set; }
    }
}
