DROP TABLE IntervencoesEquipas, 
            Intervencoes, 
            DescricoesIntervencoes, 
            EstadosIntervencoes,
            PrecosActivos, 
            Activos, 
            Membros,
            Equipas, 
            Competencias, 
            Gestores, 
            Equipas, 
            Funcionarios